# -*- coding: utf-8 -*-
{
	"name" : "ALL POS Reports in Odoo (POS BOX Compatible)",
	"version" : "17.0",
	"category" : "Point of Sale",
	"depends" : ['base','sale','point_of_sale'],
	"author": "Xrero",
	'summary': 'All in one pos reports Print pos session report pos sales summery report pos sales reports point of sales reports pos X Report pos z report pos payment summary reports pos Inventory audit report pos Order summary report pos Posted Session POS Profit Report',
	"description": """
	odoo Print POS Reports print pos reports odoo all in one pos reports
    odoo point of sales reports pos reports print pos report print
	odoo pos sales summary report pos summary report pos Session and Inventory audit report
    odoo pos audit report pos Product summary report
	""",
	"website" : "https://www.xrero.com",
	"data": [
		'security/ir.model.access.csv',
		'views/pos_reports.xml',
		'wizard/pos_sale_summary.xml',
		'wizard/sales_summary_report.xml',
		'wizard/x_report_view.xml',
		'wizard/z_report_view.xml',
		'wizard/top_selling.xml',
		'wizard/top_selling_report.xml',
		'wizard/profit_loss_report.xml',
		'wizard/pos_payment_report.xml',
		'wizard/profit_loss.xml',
		'wizard/pos_payment.xml',
	],
	'assets': {
		'point_of_sale._assets_pos': [
			'xrero_pos_reports/static/src/css/reports.css',
			'xrero_pos_reports/static/src/js/models.js',
			'xrero_pos_reports/static/src/js/AuditReport/ReportLocationButtonWidget.js',
			'xrero_pos_reports/static/src/js/AuditReport/PopupLocationWidget.js',
			'xrero_pos_reports/static/src/js/AuditReport/LocationReceiptScreen.js',
			'xrero_pos_reports/static/src/js/AuditReport/LocationReceipt.js',
			'xrero_pos_reports/static/src/js/CategorySummary/ReportCategoryButtonWidget.js',
			'xrero_pos_reports/static/src/js/CategorySummary/PopupCategoryWidget.js',
			'xrero_pos_reports/static/src/js/CategorySummary/CategoryReceiptWidget.js',
			'xrero_pos_reports/static/src/js/CategorySummary/XMLPosCategorySummaryReceipt.js',
			'xrero_pos_reports/static/src/js/OrderSummary/ReportOrderButtonWidget.js',
			'xrero_pos_reports/static/src/js/OrderSummary/PopupOrderWidget.js',
			'xrero_pos_reports/static/src/js/OrderSummary/OrderReceiptWidget.js',
			'xrero_pos_reports/static/src/js/OrderSummary/XMLPosOrderSummaryReceipt.js',
			'xrero_pos_reports/static/src/js/PaymentReport/ReportPaymentButtonWidget.js',
			'xrero_pos_reports/static/src/js/PaymentReport/PaymentSummaryPopup.js',
			'xrero_pos_reports/static/src/js/PaymentReport/PaymentReceiptWidget.js',
			'xrero_pos_reports/static/src/js/PaymentReport/XMLPosPaymentSummaryReceipt.js',
			'xrero_pos_reports/static/src/js/ReportProductButton/ReportProductButtonWidget.js',
			'xrero_pos_reports/static/src/js/ReportProductButton/PopupProductWidget.js',
			'xrero_pos_reports/static/src/js/ReportProductButton/ProductReceiptWidget.js',
			'xrero_pos_reports/static/src/js/ReportProductButton/XMLPosProductSummaryReceipt.js',
			'xrero_pos_reports/static/src/xml/AuditReport.xml',
			'xrero_pos_reports/static/src/xml/CategoryReport.xml',
			'xrero_pos_reports/static/src/xml/OrderReport.xml',
			'xrero_pos_reports/static/src/xml/PaymentReport.xml',
			'xrero_pos_reports/static/src/xml/ProductReport.xml',
		],
	},
	"auto_install": False,
	"installable": True,
	"images":['static/description/icon.png'],
}
